name: my_profile
description: A Flutter Test Task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '3.13.2'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/get_it
  # This is a simple Service Locator for Dart and Flutter projects.
  get_it: ^7.6.4

  # https://pub.dev/packages/flutter_bloc
  # It is a design pattern which helps to separate the presentation/UI layer from the business logic.
  flutter_bloc: ^8.1.3

  # https://pub.dev/packages/google_fonts
  # A Flutter package to use fonts from fonts.google.com.
  google_fonts: ^5.1.0

  # https://pub.dev/packages/flutter_svg
  # Draw SVG files using Flutter.
  flutter_svg: ^2.0.7

  # https://pub.dev/packages/shared_preferences
  # Wraps platform-specific persistent storage for simple data (NSUserDefaults on iOS and macOS, SharedPreferences on Android, etc.).
  shared_preferences: ^2.2.1

  # https://pub.dev/packages/flutter_secure_storage
  # Used to save data in encrypted shared preference.
  flutter_secure_storage: ^9.0.0

  # https://pub.dev/packages/json_serializable
  # Provides Dart Build System builders for handling JSON.
  json_serializable: ^6.7.1

  # https://pub.dev/packages/json_annotation
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.1

  # https://pub.dev/packages/loading_indicator
  # A collection of out of the box loading animations written in pure dart, no extra dependency, inspired by loaders.css and NVActivityIndicatorView.
  loading_indicator: ^3.1.1

  # https://pub.dev/packages/image_picker
  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^1.0.4

  # https://pub.dev/packages/permission_handler
  # This plugin provides a cross-platform (iOS, Android) API to request permissions and check their status.
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  # https://pub.dev/packages/build_runner
  # The build_runner package provides a concrete way of generating files using Dart code
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

